import localFont from "next/font/local";
import { Sora } from "next/font/google";
import "./globals.css";

const naas = localFont({
  variable: "--font-naas",
  src: [
    { path: "../public/fonts/NHaasGroteskTXPro-55Rg.woff2", weight: "400" },
    { path: "../public/fonts/NHaasGroteskTXPro-65Md.woff2", weight: "500" },
    { path: "../public/fonts/NHaasGroteskDSPro-55Rg.woff2", weight: "400" },
  ],
});

const sora = Sora({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-sora",
});

export const metadata = {
  title: "Apptexlab Pvt Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.variable} ${naas.variable}`}>{children}</body>
    </html>
  );
}
